<a href="https://colab.research.google.com/github/christiancamposn/Manipulacion-y-Analisis-de-Datos-con-Pandas-y-Python-/blob/main/02_Primeros_pasos_con_Google_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
10+3

13

In [2]:
2*3

6

In [3]:
2**3

8

In [4]:
x = 12
x

12

In [5]:
y = 15

In [6]:
x + y

27

In [7]:
'Hola mundo'

'Hola mundo'

In [8]:
x = 'Hola'
y = 'Mundo'

In [9]:
x + ' ' + y

'Hola Mundo'

In [10]:
[1, 2, 3, 5, 6]

[1, 2, 3, 5, 6]

In [11]:
[1, 2, 3, 4] + [2, 3, 4]

[1, 2, 3, 4, 2, 3, 4]

In [12]:
lista = [1, 2, 3, 4, 5]

In [13]:
lista[0]

1

In [14]:
lista[2]

3

In [15]:
lista[-1]

5

In [18]:
[1, 2, 3, 4, 5 ] + [10]

[1, 2, 3, 4, 5, 10]

In [19]:
import numpy as np

In [20]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [22]:
np.array([1, 2, 3, 4, 5 ] )+ 10

array([11, 12, 13, 14, 15])

In [23]:
np.array([1, 2, 3, 4, 5]).shape

(5,)

In [26]:
np.array([[1, 2, 3, 4 ], [6, 7, 8, 9]])

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [27]:
np.array([[1, 2, 3, 4 ], [6, 7, 8, 9]]).shape

(2, 4)

In [28]:
np.array([[1, 2, 3, 4 ], [6, 7, 8, 9]])[0]

array([1, 2, 3, 4])

In [30]:
np.array([[1, 2, 3, 4 ], [6, 7, 8, 9]])[0][2]

3